language: java
sudo: false
install: true
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
dist: trusty
addons:
  sonarcloud:
    organization: ranolp_github
    token:
      secure: "qa/Mr9Roo51KLM7q1SsaxUCXnvX59BfMqx7WrqHIDFrdw2CT8sj4wGj5G9AEBqgaRoL/D+xHUGG1puUxtPiTc5QAGMh87PdmdgvHaB/rfpu8YjBbmnexI5GK8pJ1SUw+Yxdn1Pq3S1y6W0Gi88PZBjihxsFEE1N9r03HIOMLBEeUok0Dw953RVy6TYD4VGkpYZoW6u3VBX7q8W7FHP7vIy/gS25j/c9g4mUUWU9kvCBE8tmV/A05ex9QBPPzDjIkOjhrfNdCZLKPFM0j9QT99OBFo5cUMrRVFnLRh3fFfkvsQfGFbpP+T3lL9G5cJw6pvDR62cNBgg0uu2rULtcz6JIVwFz2ekuj+PmpcIpD2EEAOZ+nRGCSocJsMHSO3usq6PLOFSWQF22AyxgaalCbfhtEC7GQ4+W9722v3Im4uiHZsLr0G7eCCqdBxrqHKc75jjB7u2tutnB+RYQ20UM/qrv+f3i83zsjTe0iraxgCPR7HZBplooUWdSeVyB7xrAREl2rXqiwXmpYUzXMqBifPxW71ZbYs3mOO8qOKiT1ARc6ljykKwC0pfppgBjbQf12leXxo72XdU/aK7+O0wjfGenEXmYkA28Y8m+tgUaRyaZwYqDbEpzcL7L+SY7e2ULrcNxrGWgRley1f2Bs7LVY0ayjV2UBDPyu9gywutfzIqk="
script:
  - gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'